### PR TITLE
Search type string correction

### PR DESCRIPTION
**Pull request by BrunoMine**
This is probably an imperceptible error, but I noticed when using the API.

### CODE REVIEW

**Comment by diogo-gomes** [comment]
I have to rename your branch to  hotfix/search-type-string. This way it's more easy to understand that is a hotfix in search type string.

Please, open another pull request to keep in your user history.

**Comment by LNJ2** [comment]
I think it's ok not to add a 'hotfix/' to the branch name (at least I don't think we should close pull-requests not doing this). But I don't think everyone should create new branches on the main repo, just fork this repo, add your fork as a second remote to your local check out and push your new branches to your personal repo.

That's just my opinion, I also can live with @diogo-gomes's.

**Comment by diogo-gomes** [comment]
Thanks for your opinion @LNJ2 

The main reason wasn't add "hotfix/" but replace "BrunoMine-patch-1" to "search-type-string".

The pull request auto-close when I've deleted branch BrunoMine-patch-1 (I don't mean to close but replace branch name).

I agree that everyone must fork the repository and merge from fork to main mob-engine. I'll change permissions and create an issue to discuss contributing guidelines.

**Comment by LNJ2** [comment]
> The main reason wasn't add "hotfix/" but replace "BrunoMine-patch-1" to "search-type-string".
> 
> The pull request auto-close when I've deleted branch BrunoMine-patch-1 (I don't mean to close but replace branch name).

Ok, then I can understand you, unfortunaly you can't change the source branch.

> I agree that everyone must fork the repository and merge from fork to main mob-engine. I'll create an issue to discuss contributing guidelines.

No need to open an issue for that since only those with write access can do that.

**Pull request closed without merging**
